//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqtd.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResult
    {
        public int QuestionID { get; set; }
        public Nullable<int> ServeyID { get; set; }
        public string Question { get; set; }
        public Nullable<int> VoteCount { get; set; }
        public Nullable<System.DateTime> VoteLastTime { get; set; }
    }
}
