//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqtd.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyOtherOpininon
    {
        public int OtherOID { get; set; }
        public string OtherOpinion { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public Nullable<System.DateTime> SumitTime { get; set; }
    }
}
